// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY1_1dSs00h6N1KqL7i7epQsab70yCHNc',
    appId: '1:902658804253:android:636f3c098e1a9c82a814f4',
    messagingSenderId: '902658804253',
    projectId: 'convive-piso-app',
    storageBucket: 'convive-piso-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-Fx4-GxwKZCgIgFE8IBeW6KreTk0Lj4',
    appId: '1:902658804253:ios:7f4a2d9f9d2eb097a814f4',
    messagingSenderId: '902658804253',
    projectId: 'convive-piso-app',
    storageBucket: 'convive-piso-app.firebasestorage.app',
    iosBundleId: 'com.convive.convive',
  );

  // Solo para desarrollo local (flutter run -d chrome) -- no forma parte de
  // ningún build de producción (Android/iOS via Sideloadly), así que la API
  // key aquí no es más sensible que la de Android/iOS de arriba: las tres
  // están protegidas por las reglas de Firestore/Functions, no por ser
  // secretas (son públicas por diseño en cualquier app cliente de Firebase).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1PtKwy7qvV5ExfIyR6M2otONINSLxI_8',
    appId: '1:902658804253:web:e831869e4f8adbdaa814f4',
    messagingSenderId: '902658804253',
    projectId: 'convive-piso-app',
    authDomain: 'convive-piso-app.firebaseapp.com',
    storageBucket: 'convive-piso-app.firebasestorage.app',
  );
}
